//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Comments = new HashSet<Comment>();
            this.Requests = new HashSet<Request>();
            this.readers = new HashSet<reader>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public Nullable<int> Year { get; set; }
        public string File { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<reader> readers { get; set; }
    }
}
